# Generated by Django 2.0.1 on 2018-01-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
