# Generated by Django 2.0.1 on 2018-01-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_auto_20180123_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='chat_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(unique=True),
        ),
    ]
