# Generated by Django 2.0.1 on 2018-01-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_auto_20180123_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
